### PR TITLE
Added the option to show the Jitsi-Meet Ribbon in every Appointment …

### PR DESCRIPTION
**Pull request by derstaubige**
…via the config file. so every user can decide if they want the jitsi-meet ribbon to show up in every appointment they make or not via the config file.

Basicly i wanted to have the same feature as your Issues #38 https://github.com/timetheoretical/jitsi-meet-outlook/issues/38 

This is my first pull request and my first C# thingy, i hope everything worked as planned. i would appreciate every bit of feedback :)

### CODE REVIEW

**Comment by derstaubige** [comment]
I feel like i somehow messed my commit up :-/ just to be sure, i added in the settings the boolean value "showRibbonOnEveryAppointment" with the default value "False" and i changed line 73 in the file jitsi-meet-outlook/JitsiMeetOutlook/AppointmentRibbonGroup.Designer.cs to 
this.groupJitsiMeet.Visible = Properties.Settings.Default.showRibbonOnEveryAppointment;
this part doesnt seem to got commited :-(

**Comment by timetheoretical** [comment]
Many thanks for your initiative @derstaubige ! At a first glance it seems like you have managed to think of everything (initialisation, settings, installer, languages, etc.). Well done. :)

I will have a proper look through this, hopefully this weekend. In principle it is better to undo your commits if they contain mistakes, rather than creating new commits that correct mistakes in previous ones -- that way it becomes easier to read the development history

**Comment by nordish1** [comment]
Is there anything new yet?

**Comment by Labi4** [comment]
that is really interesting topic. will you have time to implement it at near future? 
at vet 0.6 it's not available (

**Pull request closed without merging**
