### PR TITLE
Added phone and pin code functionality

### PR DESCRIPTION
**Pull request by fmuscetra**
**Note to this pull request**
This fork of version 0.6.5 adds:

- Phone number and PIN code for the dial-in gateway included in the invitation
- Function that calculates the PIN code based on sha-2
- Updated configuration panel that includes the possibility to configure the phone number

### CODE REVIEW

**Comment by timetheoretical** [comment]
Looks good. Why did you change the default domain from `defaultDomain = "meet.jit.si";` to `defaultDomain = "jitsi.domain.com";`

**Comment by fmuscetra** [comment]
I wanted simply to hide our domain (we have our Jitsi deployment) but I forgot to put back the meet.jit.si domain.
You can change it.

However, I'm not sure if meet.jit.si implements the hashing algorithm (SHA-2) to generate the pin code. We implemented it on Jitsi server side too and clearly the PIN code generated by Timetheoretical Outlook plugin matches the one calculated by the Jitsi server.

**Comment by timetheoretical** [comment]
I see, yes it would be good to change the domain back to the default then.

Also, it would be good to check whether the hashing algorithm produces the same PIN. I would be hesitant to deploy something that does not work with the default server

**Comment by fmuscetra** [comment]
I don't have time at the moment to test it with the meet.jit.si public server, but you can do it. 
I wanted simply to make the code available to everybody in case of interest.

**Comment by timetheoretical** [comment]
I guess this is covered by #55 ; should I close this PR now @fmuscetra ?

**Comment by fmuscetra** [comment]
> I guess this is covered by #55 ; should I close this PR now @fmuscetra ?

Yes, correct.

**Pull request closed without merging**
